### ISSUE TITLE
вапрос

### ISSUE THREAD

**Issue by tailsjs** [TheEVolk/yandex-alice-client#1]
а чисто в теории: поддерживает навыки?

**Comment by TheEVolk** [comment]
<img width="923" alt="image" src="https://user-images.githubusercontent.com/16771498/215597294-20da241f-54e9-44f6-a82a-c42a5fdd49c7.png">
Поддерживает и на практике, хотя, стоило бы сохранять ID диалога, а то Алиса теряет контекст. Но и это мы обновим.
