### ISSUE TITLE
При Message timeout не возвращается ошибка.

### ISSUE THREAD

**Issue by tailsjs** [TheEVolk/yandex-alice-client#4]
Если Алиса не смогла вернуть ответ, то единственное что делает код - Просто выводит в консоль ошибку про таймаут.

**Comment by TheEVolk** [comment]
На то она и ошибка, нет ответа - код зависает. Оттого и таймаут.

**Comment by tailsjs** [comment]
Ну так в том то проблема, что я не могу её отловить через код.

**Comment by TheEVolk** [comment]
вообще таймаут вызывает reject 
https://github.com/TheEVolk/yandex-alice-client/blob/main/src/uniproxy.ts#L69

**Comment by tailsjs** [comment]
Попробовал словить, сейчас вроде словилось, хотя до этого код не ловил.
